#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# EtherOS Sprint 3B — ISP Branding Layer
# Paste this entire script into your VPS terminal (root@72.62.160.72)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

EDGE_DIR="/opt/etheros-edge"
GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; RED='\033[0;31m'; NC='\033[0m'

echo -e "${CYAN}${BOLD}━━━ EtherOS Sprint 3B — ISP Branding Layer ━━━${NC}"
echo ""

# ── Create directories ────────────────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Creating directories..."
mkdir -p "$EDGE_DIR/isp-config"
chmod 750 "$EDGE_DIR/isp-config"
echo -e "  ${GREEN}✓${NC} /opt/etheros-edge/isp-config/"

# ── Write nginx vhost template ────────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing nginx tenant vhost template..."
cat > "$EDGE_DIR/nginx/tenant-vhost.conf.template" << 'TMPL'
# EtherOS ISP Tenant vhost — __SLUG__
# Auto-generated by add-isp-tenant.sh — do not edit manually

upstream openwebui___SLUG__ {
    server etheros-open-webui:8080;
}

server {
    listen 443 ssl http2;
    server_name __DOMAIN__;

    ssl_certificate     /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    client_max_body_size 100M;
    proxy_read_timeout   300s;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-ISP-Tenant "__SLUG__" always;
    add_header X-ISP-Name "__ISP_NAME__" always;
    add_header X-ISP-Accent "__ACCENT_COLOR__" always;

    location /api/ {
        proxy_pass         http://openwebui___SLUG__/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-ISP-Tenant "__SLUG__";
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }

    location /ws/ {
        proxy_pass         http://openwebui___SLUG__/ws/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-ISP-Tenant "__SLUG__";
        proxy_read_timeout 86400;
    }

    location / {
        proxy_pass         http://openwebui___SLUG__;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-ISP-Tenant "__SLUG__";
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }

    location /health {
        return 200 '{"status":"ok","tenant":"__SLUG__"}';
        add_header Content-Type application/json;
    }
}

server {
    listen 80;
    server_name __DOMAIN__;
    return 301 https://$host$request_uri;
}
TMPL
echo -e "  ${GREEN}✓${NC} nginx/tenant-vhost.conf.template"

# ── Write default EtherOS tenant config ──────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing default EtherOS tenant config..."
cat > "$EDGE_DIR/isp-config/etheros-default.json" << 'JSON'
{
  "slug": "etheros-default",
  "name": "EtherOS AI",
  "domain": "edge.etheros.ai",
  "logo_url": "",
  "accent_color": "#00C2CB",
  "primary_color": "#0D1B2A",
  "support_email": "support@etheros.ai",
  "plan_personal_price": 49,
  "plan_professional_price": 99,
  "max_terminals": 1000
}
JSON
echo -e "  ${GREEN}✓${NC} isp-config/etheros-default.json"

# ── Write add-isp-tenant.sh ───────────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing add-isp-tenant.sh..."
cat > "$EDGE_DIR/add-isp-tenant.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

EDGE_DIR="/opt/etheros-edge"
ISP_CONFIG_DIR="$EDGE_DIR/isp-config"
NGINX_CONF_DIR="$EDGE_DIR/nginx/conf.d"
TEMPLATE="$EDGE_DIR/nginx/tenant-vhost.conf.template"

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; RED='\033[0;31m'; NC='\033[0m'

usage() {
    echo -e "${BOLD}Usage:${NC} $0 --slug <slug> --name <name> --domain <domain> [--accent <hex>]"
    echo ""
    echo "  --slug    Lowercase slug (letters, numbers, hyphens)  e.g. valley-fiber"
    echo "  --name    Display name                                e.g. \"Valley Fiber\""
    echo "  --domain  Full domain for this ISP's portal           e.g. edge.valleyfiber.com"
    echo "  --accent  Accent hex color (optional, default #00C2CB)"
    echo ""
    echo -e "${BOLD}Example:${NC}"
    echo "  $0 --slug valley-fiber --name \"Valley Fiber\" --domain edge.valleyfiber.com"
    exit 1
}

SLUG=""; NAME=""; DOMAIN=""; ACCENT="#00C2CB"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --slug)   SLUG="$2";   shift 2 ;;
        --name)   NAME="$2";   shift 2 ;;
        --domain) DOMAIN="$2"; shift 2 ;;
        --accent) ACCENT="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo -e "${RED}Unknown argument: $1${NC}"; usage ;;
    esac
done

[[ -z "$SLUG" || -z "$NAME" || -z "$DOMAIN" ]] && { echo -e "${RED}Error: --slug, --name, --domain required${NC}"; echo ""; usage; }
[[ ! "$SLUG" =~ ^[a-z0-9-]+$ ]] && { echo -e "${RED}Error: slug must be lowercase letters/numbers/hyphens only${NC}"; exit 1; }

echo -e "${CYAN}${BOLD}━━━ Adding ISP Tenant ━━━${NC}"
echo -e "  Slug:    ${SLUG}"
echo -e "  Name:    ${NAME}"
echo -e "  Domain:  ${DOMAIN}"
echo -e "  Accent:  ${ACCENT}"
echo ""

mkdir -p "$ISP_CONFIG_DIR" "$NGINX_CONF_DIR"

# Write JSON config
CONFIG_FILE="$ISP_CONFIG_DIR/${SLUG}.json"
echo -e "${YELLOW}▸${NC} Writing config → $CONFIG_FILE"
cat > "$CONFIG_FILE" << JSONEOF
{
  "slug": "${SLUG}",
  "name": "${NAME}",
  "domain": "${DOMAIN}",
  "logo_url": "",
  "accent_color": "${ACCENT}",
  "primary_color": "#0D1B2A",
  "support_email": "support@${DOMAIN#edge.}",
  "plan_personal_price": 49,
  "plan_professional_price": 99,
  "max_terminals": 500
}
JSONEOF
echo -e "  ${GREEN}✓${NC} Config saved"

# Generate nginx vhost from template
if [[ ! -f "$TEMPLATE" ]]; then
    echo -e "${RED}Error: template not found at $TEMPLATE${NC}"
    exit 1
fi

VHOST_FILE="$NGINX_CONF_DIR/${SLUG}.conf"
echo -e "${YELLOW}▸${NC} Generating nginx vhost → $VHOST_FILE"
sed \
    -e "s|__DOMAIN__|${DOMAIN}|g" \
    -e "s|__SLUG__|${SLUG}|g" \
    -e "s|__ISP_NAME__|${NAME}|g" \
    -e "s|__ACCENT_COLOR__|${ACCENT}|g" \
    "$TEMPLATE" > "$VHOST_FILE"
echo -e "  ${GREEN}✓${NC} Vhost generated"

# Test nginx config
echo -e "${YELLOW}▸${NC} Testing nginx config..."
docker exec etheros-nginx nginx -t 2>&1 | grep -E "successful|error" || true

# Reload nginx
echo -e "${YELLOW}▸${NC} Reloading nginx..."
docker exec etheros-nginx nginx -s reload
echo -e "  ${GREEN}✓${NC} Nginx reloaded"

echo ""
echo -e "${GREEN}${BOLD}━━━ Tenant '${SLUG}' Added ━━━${NC}"
echo -e "  Config:  $CONFIG_FILE"
echo -e "  Vhost:   $VHOST_FILE"
echo ""
echo -e "${CYAN}Next steps for this tenant:${NC}"
echo "  1. Point DNS: ${DOMAIN} → 72.62.160.72 (A record)"
echo "  2. Get cert:  certbot certonly --webroot -w /var/www/html -d ${DOMAIN}"
echo "     (or)       certbot certonly --standalone --preferred-challenges http -d ${DOMAIN}"
SCRIPT
chmod +x "$EDGE_DIR/add-isp-tenant.sh"
echo -e "  ${GREEN}✓${NC} add-isp-tenant.sh"

# ── Write list-isp-tenants.sh ─────────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing list-isp-tenants.sh..."
cat > "$EDGE_DIR/list-isp-tenants.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
EDGE_DIR="/opt/etheros-edge"
ISP_CONFIG_DIR="$EDGE_DIR/isp-config"
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'; YELLOW='\033[1;33m'

echo -e "${CYAN}${BOLD}━━━ EtherOS ISP Tenants ━━━${NC}"
printf "%-20s %-25s %-35s %-10s\n" "SLUG" "NAME" "DOMAIN" "MAX TERMS"
printf "%-20s %-25s %-35s %-10s\n" "────────────────────" "─────────────────────────" "───────────────────────────────────" "──────────"

shopt -s nullglob
configs=("$ISP_CONFIG_DIR"/*.json)
if [[ ${#configs[@]} -eq 0 ]]; then
    echo -e "${YELLOW}No ISP tenants configured yet.${NC}"
    echo "Run: ./add-isp-tenant.sh --slug myisp --name \"My ISP\" --domain edge.myisp.com"
    exit 0
fi

for f in "${configs[@]}"; do
    slug=$(python3 -c "import json,sys; d=json.load(open('$f')); print(d.get('slug','?'))")
    name=$(python3 -c "import json,sys; d=json.load(open('$f')); print(d.get('name','?'))")
    domain=$(python3 -c "import json,sys; d=json.load(open('$f')); print(d.get('domain','?'))")
    maxterm=$(python3 -c "import json,sys; d=json.load(open('$f')); print(d.get('max_terminals','?'))")
    printf "%-20s %-25s %-35s %-10s\n" "$slug" "$name" "$domain" "$maxterm"
done
echo ""
echo -e "Total: ${#configs[@]} tenant(s)"
SCRIPT
chmod +x "$EDGE_DIR/list-isp-tenants.sh"
echo -e "  ${GREEN}✓${NC} list-isp-tenants.sh"

# ── Write remove-isp-tenant.sh ────────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing remove-isp-tenant.sh..."
cat > "$EDGE_DIR/remove-isp-tenant.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
EDGE_DIR="/opt/etheros-edge"
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

SLUG=""
while [[ $# -gt 0 ]]; do
    case "$1" in --slug) SLUG="$2"; shift 2 ;; *) echo "Usage: $0 --slug <slug>"; exit 1 ;; esac
done
[[ -z "$SLUG" ]] && { echo "Usage: $0 --slug <slug>"; exit 1; }
[[ "$SLUG" == "etheros-default" ]] && { echo -e "${RED}Cannot remove the default EtherOS tenant.${NC}"; exit 1; }

echo -e "${YELLOW}Removing tenant: ${SLUG}${NC}"
CONFIG="$EDGE_DIR/isp-config/${SLUG}.json"
VHOST="$EDGE_DIR/nginx/conf.d/${SLUG}.conf"
[[ -f "$CONFIG" ]] && rm "$CONFIG" && echo -e "  ${GREEN}✓${NC} Removed $CONFIG" || echo "  Config not found (already removed?)"
[[ -f "$VHOST" ]]  && rm "$VHOST"  && echo -e "  ${GREEN}✓${NC} Removed $VHOST"  || echo "  Vhost not found (already removed?)"
docker exec etheros-nginx nginx -s reload && echo -e "  ${GREEN}✓${NC} Nginx reloaded"
echo -e "${GREEN}Tenant '${SLUG}' removed.${NC}"
SCRIPT
chmod +x "$EDGE_DIR/remove-isp-tenant.sh"
echo -e "  ${GREEN}✓${NC} remove-isp-tenant.sh"

# ── Write docker-compose-patch.py ─────────────────────────────────────────────
echo -e "${YELLOW}▸${NC} Writing docker-compose-patch.py..."
cat > "$EDGE_DIR/docker-compose-patch.py" << 'PYEOF'
#!/usr/bin/env python3
"""Patch docker-compose.yml to set WEBUI_ISP_TENANT env var on the open-webui service."""
import argparse, shutil, sys, yaml
from pathlib import Path

COMPOSE = Path("/opt/etheros-edge/docker-compose.yml")

parser = argparse.ArgumentParser(description="Set WEBUI_ISP_TENANT in docker-compose.yml")
parser.add_argument("--slug", required=True, help="ISP tenant slug")
args = parser.parse_args()

# Backup
backup = COMPOSE.with_suffix(".yml.bak")
shutil.copy2(COMPOSE, backup)
print(f"Backup: {backup}")

data = yaml.safe_load(COMPOSE.read_text())
services = data.get("services", {})

# Find open-webui service
owui_key = next((k for k in services if "open-webui" in k or "openwebui" in k.lower()), None)
if not owui_key:
    print(f"ERROR: open-webui service not found. Services: {list(services.keys())}", file=sys.stderr)
    sys.exit(1)

svc = services[owui_key]
env = svc.get("environment", [])

# Convert list-style env to dict if needed
if isinstance(env, list):
    env_dict = {}
    for e in env:
        if "=" in e:
            k, v = e.split("=", 1)
            env_dict[k] = v
        else:
            env_dict[e] = None
    env = env_dict

env["WEBUI_ISP_TENANT"] = args.slug
svc["environment"] = env
print(f"Set WEBUI_ISP_TENANT={args.slug} on service '{owui_key}'")

COMPOSE.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))
print(f"Wrote {COMPOSE}")
print("Run: cd /opt/etheros-edge && docker compose up -d --no-deps --force-recreate open-webui")
PYEOF
chmod +x "$EDGE_DIR/docker-compose-patch.py"
echo -e "  ${GREEN}✓${NC} docker-compose-patch.py"

# ── Write README ──────────────────────────────────────────────────────────────
cat > "$EDGE_DIR/README-3B.md" << 'DOC'
# EtherOS Sprint 3B — ISP Branding Layer

## Overview
Each ISP gets their own branded portal at a custom domain (e.g. edge.valleyfiber.com).
The branding config drives: ISP name, accent color, logo URL, and domain routing.

## Quick Start: Add a New ISP Tenant

```bash
cd /opt/etheros-edge

# 1. Add the tenant (creates JSON config + nginx vhost)
./add-isp-tenant.sh --slug valley-fiber --name "Valley Fiber" --domain edge.valleyfiber.com

# 2. Point the ISP's DNS: edge.valleyfiber.com → 72.62.160.72

# 3. Get a TLS cert for the new domain
certbot certonly --standalone --preferred-challenges http -d edge.valleyfiber.com

# 4. Reload nginx to pick up the new cert
docker exec etheros-nginx nginx -s reload
```

## Config Schema (isp-config/{slug}.json)
| Field                  | Description                              |
|------------------------|------------------------------------------|
| slug                   | URL-safe identifier (e.g. valley-fiber)  |
| name                   | Display name shown in the UI             |
| domain                 | Full domain for this ISP's portal        |
| accent_color           | Hex color for teal accent (#00C2CB)      |
| primary_color          | Hex color for nav/header (#0D1B2A)       |
| logo_url               | URL to ISP logo image (optional)         |
| support_email          | Auto-populated from domain               |
| plan_personal_price    | $/yr for personal plan (default 49)      |
| plan_professional_price| $/yr for professional plan (default 99)  |
| max_terminals          | Terminal cap for this ISP (default 500)  |

## Other Commands
```bash
./list-isp-tenants.sh           # Show all configured tenants
./remove-isp-tenant.sh --slug valley-fiber   # Remove a tenant
python3 docker-compose-patch.py --slug valley-fiber  # Set active tenant in docker-compose
```

## How Nginx Vhost Injection Works
add-isp-tenant.sh reads nginx/tenant-vhost.conf.template and substitutes:
  __DOMAIN__      → actual domain
  __SLUG__        → tenant slug
  __ISP_NAME__    → display name
  __ACCENT_COLOR__ → hex accent color

The generated .conf is written to nginx/conf.d/{slug}.conf and nginx reloads automatically.
ISP identity headers (X-ISP-Tenant, X-ISP-Name, X-ISP-Accent) are injected on every request.
DOC

# ── Final verification ────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}▸${NC} Running verification..."
echo ""
echo -e "${CYAN}Scripts installed:${NC}"
ls -la "$EDGE_DIR"/*.sh "$EDGE_DIR"/*.py 2>/dev/null | awk '{print "  " $NF, $1}'
echo ""
echo -e "${CYAN}ISP configs:${NC}"
ls "$EDGE_DIR/isp-config/"
echo ""
echo -e "${CYAN}Nginx template:${NC}"
[[ -f "$EDGE_DIR/nginx/tenant-vhost.conf.template" ]] && echo -e "  ${GREEN}✓${NC} tenant-vhost.conf.template present" || echo -e "  ${RED}✗${NC} template MISSING"
echo ""

# Quick test: list tenants
echo -e "${YELLOW}▸${NC} Listing tenants..."
bash "$EDGE_DIR/list-isp-tenants.sh"

echo ""
echo -e "${GREEN}${BOLD}━━━ Sprint 3B Fully Deployed ━━━${NC}"
echo ""
echo -e "${CYAN}To add your first real ISP tenant:${NC}"
echo "  cd /opt/etheros-edge"
echo "  ./add-isp-tenant.sh --slug valley-fiber --name \"Valley Fiber\" --domain edge.valleyfiber.com"
echo ""
echo -e "${CYAN}Docs:${NC} cat /opt/etheros-edge/README-3B.md"
